server:
  port: 7001
#spring:
#  redis:
#    cluster:
#      nodes: 116.62.144.245:30001, 116.62.144.245:30002,116.62.144.245:30003,116.62.144.245:30004,116.62.144.245:30005,116.62.144.245:30006
#    # 新版
#    jedis:
#      pool:
#        max-wait: -1
#        max-active: 300
#        max-idle: 100
#        min-idle: 20
### 连接超时时间（毫秒）
#    timeout: 60000
### Redis数据库索引(默认为0)
#    database: 0

#spring:
#  redis:
#    cluster:
#      # 各 Redis 节点信息
#      nodes: 116.62.144.245:30001,116.62.144.245:30002,116.62.144.245:30003,116.62.144.245:30004,116.62.144.245:30005,116.62.144.245:30006
#      # 执行命令超时时间
#      command-timeout: 15000
#      # 重试次数
#      max-attempts: 5
#      # 跨集群执行命令时要遵循的最大重定向数量
#      max-redirects: 3
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 16
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0
#      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
#      test-on-borrow: true


spring:
  redis:
    database: 2
#    host: 119.23.61.10
#    port: 8016
    host: 39.99.171.234
    port: 6380
#    cluster:
#      nodes:
#        - 116.62.144.245:30001

    #    jedis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
    password: ee88Nhk3ftYxZlrE
redis:
    hostName: localhost
    port: 6379
    password: 12345
    database: 0

redis2:
    hostName: localhost
    port: 6379
    p: 12345
    database: 0
redis3:
    hostName: localhost
    port: 6379
    password: 12345
    database: 0