server:
  port: ${random.int[1000,1999]}
#spring:
#  mqtt:
#    username: admin
#    mqpassword: public
#    host-url: tcp://111.229.120.71:18083
#    client-id: zhjsbackground${random.value}
#    default-topic: $SYS/brokers/+/clients/#
#    completionTimeout: 3000
#    keepAlive: 60
