server:
  port: 8899
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 119.23.61.10:8018
      local: false
      repositories:
        enabled: true
      client-transport-sniff=: false

es:
  index: user_2
  alias: user
