server:
  port: 8888
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 47.52.198.122:9300
      local: false
      repositories:
        enabled: true
      client-transport-sniff=: false
