server:
  port: 8888
spring:
  data:
    elasticsearch:
      cluster-name: es
      cluster-nodes: 119.23.61.10:8012
      local: false
      repositories:
        enabled: true
      client-transport-sniff=: false
