server:
  port: 8888

redis:
    hostName: localhost
    port: 6379
    password: 12345
    database: 0

redis2:
    hostName: localhost
    port: 6379
    p: 12345
    database: 0
redis3:
    hostName: localhost
    port: 6379
    password: 12345
    database: 0