spring:
  rabbitmq:
    username: guest
    password: guest
#    支持发布确认
    publisher-confirms: true
#    支持发布返回
    publisher-returns: true
    listener:
      simple:
#      采用手动应答
        acknowledge-mode: manual
#        当前监听容器数
        concurrency: 1
#        最大数
        max-concurrency: 1
#        是否支持重试
        retry:
          enabled: true
    host: 119.23.167.190
server:
  port: 8888
