#zookeeper:
#  enabled: true
#  #zookeeper.server: 47.106.106.53:9036,47.106.106.53:9037,47.106.106.53:9038
#  server: 119.23.61.10:2181
#  namespace: demo
#  digest: rt:rt                     #zkCli.sh acl 命令 addauth digest mpush
#  sessionTimeoutMs: 1000            #会话超时时间，单位为毫秒，默认60000ms,连接断开后，其它客户端还能请到临时节点的时间
#  connectionTimeoutMs: 6000         #连接创建超时时间，单位为毫秒
#  maxRetries: 3                     #最大重试次数
#  baseSleepTimeMs: 1000             #初始sleep时间 ,毫秒
server:
  port: 8186