// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.w77996.protobuf.protobuf;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 Id = 1;
    boolean hasId();
    int getId();
    
    // optional int64 UserId = 2;
    boolean hasUserId();
    long getUserId();
    
    // optional string AccountName = 3;
    boolean hasAccountName();
    String getAccountName();
    
    // optional string PhoneNum = 4;
    boolean hasPhoneNum();
    String getPhoneNum();
    
    // optional string Email = 5;
    boolean hasEmail();
    String getEmail();
    
    // optional string Password = 6;
    boolean hasPassword();
    String getPassword();
    
    // optional int32 BaseState = 7;
    boolean hasBaseState();
    int getBaseState();
    
    // optional int32 Uuid = 8;
    boolean hasUuid();
    int getUuid();
    
    // optional string OpenId = 9;
    boolean hasOpenId();
    String getOpenId();
    
    // optional int32 Type = 10;
    boolean hasType();
    int getType();
    
    // optional string AreaIds = 11;
    boolean hasAreaIds();
    String getAreaIds();
    
    // optional int32 Sex = 12;
    boolean hasSex();
    int getSex();
    
    // optional uint64 Birthday = 13;
    boolean hasBirthday();
    long getBirthday();
    
    // optional string BackCover = 14;
    boolean hasBackCover();
    String getBackCover();
    
    // optional string AnnouncerType = 15;
    boolean hasAnnouncerType();
    String getAnnouncerType();
    
    // optional string LikeTags = 16;
    boolean hasLikeTags();
    String getLikeTags();
    
    // optional int32 LikeCount = 17;
    boolean hasLikeCount();
    int getLikeCount();
    
    // optional int32 AblumnCount = 18;
    boolean hasAblumnCount();
    int getAblumnCount();
    
    // optional int32 FollowerCount = 19;
    boolean hasFollowerCount();
    int getFollowerCount();
    
    // optional int32 FollowCount = 20;
    boolean hasFollowCount();
    int getFollowCount();
    
    // optional string Remark = 21;
    boolean hasRemark();
    String getRemark();
    
    // optional string ShortRemark = 22;
    boolean hasShortRemark();
    String getShortRemark();
    
    // optional uint64 CreateTime = 23;
    boolean hasCreateTime();
    long getCreateTime();
    
    // optional uint64 UpdateTime = 24;
    boolean hasUpdateTime();
    long getUpdateTime();
    
    // optional int32 Hot = 25;
    boolean hasHot();
    int getHot();
    
    // optional string NickName = 26;
    boolean hasNickName();
    String getNickName();
    
    // optional int32 Source = 27;
    boolean hasSource();
    int getSource();
    
    // optional int32 State = 28;
    boolean hasState();
    int getState();
    
    // optional string Cover = 29;
    boolean hasCover();
    String getCover();
    
    // optional string Features = 30;
    boolean hasFeatures();
    String getFeatures();
    
    // optional int64 Flag = 31;
    boolean hasFlag();
    long getFlag();
    
    // optional int32 folderCount = 32;
    boolean hasFolderCount();
    int getFolderCount();
    
    // optional int32 collectionFolderCount = 33;
    boolean hasCollectionFolderCount();
    int getCollectionFolderCount();
    
    // optional int32 collectionReadCount = 34;
    boolean hasCollectionReadCount();
    int getCollectionReadCount();
    
    // optional int32 status = 35;
    boolean hasStatus();
    int getStatus();
    
    // optional string Uuids = 36;
    boolean hasUuids();
    String getUuids();
  }
  public static final class UserBean extends
      com.google.protobuf.GeneratedMessage
      implements UserBeanOrBuilder {
    // Use UserBean.newBuilder() to construct.
    private UserBean(Builder builder) {
      super(builder);
    }
    private UserBean(boolean noInit) {}
    
    private static final UserBean DEFAULTINSTANCE;
    public static UserBean getDefaultInstance() {
      return DEFAULTINSTANCE;
    }
    
    @Override
    public UserBean getDefaultInstanceForType() {
      return DEFAULTINSTANCE;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserProtos.internalstatictutorialUserBeandescriptor;
    }
    
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserProtos.internalstatictutorialUserBeanfieldAccessorTable;
    }

    private int bitField0;
    private int bitField1;
    // required int32 Id = 1;
    public static final int IDFIELDNUMBER = 1;
    private int id;
    @Override
    public boolean hasId() {
      return ((bitField0 & 0x00000001) == 0x00000001);
    }
    @Override
    public int getId() {
      return id;
    }

    // optional int64 UserId = 2;
    public static final int USERIDFIELDNUMBER = 2;
    private long userId;
    @Override
    public boolean hasUserId() {
      return ((bitField0 & 0x00000002) == 0x00000002);
    }
    @Override
    public long getUserId() {
      return userId;
    }

    // optional string AccountName = 3;
    public static final int ACCOUNTNAMEFIELDNUMBER = 3;
    private Object accountName;
    @Override
    public boolean hasAccountName() {
      return ((bitField0 & 0x00000004) == 0x00000004);
    }
    @Override
    public String getAccountName() {
      Object ref = accountName;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountName = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountNameBytes() {
      Object ref = accountName;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountName = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string PhoneNum = 4;
    public static final int PHONENUMFIELDNUMBER = 4;
    private Object phoneNum;
    @Override
    public boolean hasPhoneNum() {
      return ((bitField0 & 0x00000008) == 0x00000008);
    }
    @Override
    public String getPhoneNum() {
      Object ref = phoneNum;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phoneNum = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneNumBytes() {
      Object ref = phoneNum;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phoneNum = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Email = 5;
    public static final int EMAILFIELDNUMBER = 5;
    private Object email;
    @Override
    public boolean hasEmail() {
      return ((bitField0 & 0x00000010) == 0x00000010);
    }
    @Override
    public String getEmail() {
      Object ref = email;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      Object ref = email;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Password = 6;
    public static final int PASSWORDFIELDNUMBER = 6;
    private Object password;
    @Override
    public boolean hasPassword() {
      return ((bitField0 & 0x00000020) == 0x00000020);
    }
    @Override
    public String getPassword() {
      Object ref = password;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      Object ref = password;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 BaseState = 7;
    public static final int BASESTATEFIELDNUMBER = 7;
    private int baseState;
    @Override
    public boolean hasBaseState() {
      return ((bitField0 & 0x00000040) == 0x00000040);
    }
    @Override
    public int getBaseState() {
      return baseState;
    }

    // optional int32 Uuid = 8;
    public static final int UUIDFIELDNUMBER = 8;
    private int uuid;
    @Override
    public boolean hasUuid() {
      return ((bitField0 & 0x00000080) == 0x00000080);
    }
    @Override
    public int getUuid() {
      return uuid;
    }

    // optional string OpenId = 9;
    public static final int OPENIDFIELDNUMBER = 9;
    private Object openId;
    @Override
    public boolean hasOpenId() {
      return ((bitField0 & 0x00000100) == 0x00000100);
    }
    @Override
    public String getOpenId() {
      Object ref = openId;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          openId = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOpenIdBytes() {
      Object ref = openId;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        openId = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 Type = 10;
    public static final int TYPEFIELDNUMBER = 10;
    private int type;
    @Override
    public boolean hasType() {
      return ((bitField0 & 0x00000200) == 0x00000200);
    }
    @Override
    public int getType() {
      return type;
    }

    // optional string AreaIds = 11;
    public static final int AREAIDSFIELDNUMBER = 11;
    private Object areaIds;
    @Override
    public boolean hasAreaIds() {
      return ((bitField0 & 0x00000400) == 0x00000400);
    }
    @Override
    public String getAreaIds() {
      Object ref = areaIds;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          areaIds = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAreaIdsBytes() {
      Object ref = areaIds;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        areaIds = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 Sex = 12;
    public static final int SEXFIELDNUMBER = 12;
    private int sex;
    @Override
    public boolean hasSex() {
      return ((bitField0 & 0x00000800) == 0x00000800);
    }
    @Override
    public int getSex() {
      return sex;
    }

    // optional uint64 Birthday = 13;
    public static final int BIRTHDAYFIELDNUMBER = 13;
    private long birthday;
    @Override
    public boolean hasBirthday() {
      return ((bitField0 & 0x00001000) == 0x00001000);
    }
    @Override
    public long getBirthday() {
      return birthday;
    }

    // optional string BackCover = 14;
    public static final int BACKCOVERFIELDNUMBER = 14;
    private Object backCover;
    @Override
    public boolean hasBackCover() {
      return ((bitField0 & 0x00002000) == 0x00002000);
    }
    @Override
    public String getBackCover() {
      Object ref = backCover;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          backCover = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBackCoverBytes() {
      Object ref = backCover;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        backCover = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string AnnouncerType = 15;
    public static final int ANNOUNCERTYPEFIELDNUMBER = 15;
    private Object announcerType;
    @Override
    public boolean hasAnnouncerType() {
      return ((bitField0 & 0x00004000) == 0x00004000);
    }
    @Override
    public String getAnnouncerType() {
      Object ref = announcerType;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          announcerType = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAnnouncerTypeBytes() {
      Object ref = announcerType;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        announcerType = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string LikeTags = 16;
    public static final int LIKETAGSFIELDNUMBER = 16;
    private Object likeTags;
    @Override
    public boolean hasLikeTags() {
      return ((bitField0 & 0x00008000) == 0x00008000);
    }
    @Override
    public String getLikeTags() {
      Object ref = likeTags;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          likeTags = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLikeTagsBytes() {
      Object ref = likeTags;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        likeTags = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 LikeCount = 17;
    public static final int LIKECOUNTFIELDNUMBER = 17;
    private int likeCount;
    @Override
    public boolean hasLikeCount() {
      return ((bitField0 & 0x00010000) == 0x00010000);
    }
    @Override
    public int getLikeCount() {
      return likeCount;
    }

    // optional int32 AblumnCount = 18;
    public static final int ABLUMNCOUNTFIELDNUMBER = 18;
    private int ablumnCount;
    @Override
    public boolean hasAblumnCount() {
      return ((bitField0 & 0x00020000) == 0x00020000);
    }
    @Override
    public int getAblumnCount() {
      return ablumnCount;
    }

    // optional int32 FollowerCount = 19;
    public static final int FOLLOWERCOUNTFIELDNUMBER = 19;
    private int followerCount;
    @Override
    public boolean hasFollowerCount() {
      return ((bitField0 & 0x00040000) == 0x00040000);
    }
    @Override
    public int getFollowerCount() {
      return followerCount;
    }

    // optional int32 FollowCount = 20;
    public static final int FOLLOWCOUNTFIELDNUMBER = 20;
    private int followCount;
    @Override
    public boolean hasFollowCount() {
      return ((bitField0 & 0x00080000) == 0x00080000);
    }
    @Override
    public int getFollowCount() {
      return followCount;
    }

    // optional string Remark = 21;
    public static final int REMARKFIELDNUMBER = 21;
    private Object remark;
    @Override
    public boolean hasRemark() {
      return ((bitField0 & 0x00100000) == 0x00100000);
    }
    @Override
    public String getRemark() {
      Object ref = remark;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          remark = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRemarkBytes() {
      Object ref = remark;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        remark = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ShortRemark = 22;
    public static final int SHORTREMARKFIELDNUMBER = 22;
    private Object shortRemark;
    @Override
    public boolean hasShortRemark() {
      return ((bitField0 & 0x00200000) == 0x00200000);
    }
    @Override
    public String getShortRemark() {
      Object ref = shortRemark;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          shortRemark = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getShortRemarkBytes() {
      Object ref = shortRemark;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        shortRemark = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 CreateTime = 23;
    public static final int CREATETIMEFIELDNUMBER = 23;
    private long createTime;
    @Override
    public boolean hasCreateTime() {
      return ((bitField0 & 0x00400000) == 0x00400000);
    }
    @Override
    public long getCreateTime() {
      return createTime;
    }

    // optional uint64 UpdateTime = 24;
    public static final int UPDATETIMEFIELDNUMBER = 24;
    private long updateTime;
    @Override
    public boolean hasUpdateTime() {
      return ((bitField0 & 0x00800000) == 0x00800000);
    }
    @Override
    public long getUpdateTime() {
      return updateTime;
    }

    // optional int32 Hot = 25;
    public static final int HOTFIELDNUMBER = 25;
    private int hot;
    @Override
    public boolean hasHot() {
      return ((bitField0 & 0x01000000) == 0x01000000);
    }
    @Override
    public int getHot() {
      return hot;
    }

    // optional string NickName = 26;
    public static final int NICKNAMEFIELDNUMBER = 26;
    private Object nickName;
    @Override
    public boolean hasNickName() {
      return ((bitField0 & 0x02000000) == 0x02000000);
    }
    @Override
    public String getNickName() {
      Object ref = nickName;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickName = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNickNameBytes() {
      Object ref = nickName;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickName = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 Source = 27;
    public static final int SOURCEFIELDNUMBER = 27;
    private int source;
    @Override
    public boolean hasSource() {
      return ((bitField0 & 0x04000000) == 0x04000000);
    }
    @Override
    public int getSource() {
      return source;
    }

    // optional int32 State = 28;
    public static final int STATEFIELDNUMBER = 28;
    private int state;
    @Override
    public boolean hasState() {
      return ((bitField0 & 0x08000000) == 0x08000000);
    }
    @Override
    public int getState() {
      return state;
    }

    // optional string Cover = 29;
    public static final int COVERFIELDNUMBER = 29;
    private Object cover;
    @Override
    public boolean hasCover() {
      return ((bitField0 & 0x10000000) == 0x10000000);
    }
    @Override
    public String getCover() {
      Object ref = cover;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cover = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCoverBytes() {
      Object ref = cover;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cover = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Features = 30;
    public static final int FEATURESFIELDNUMBER = 30;
    private Object features;
    @Override
    public boolean hasFeatures() {
      return ((bitField0 & 0x20000000) == 0x20000000);
    }
    @Override
    public String getFeatures() {
      Object ref = features;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          features = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFeaturesBytes() {
      Object ref = features;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        features = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 Flag = 31;
    public static final int FLAGFIELDNUMBER = 31;
    private long flag;
    @Override
    public boolean hasFlag() {
      return ((bitField0 & 0x40000000) == 0x40000000);
    }
    @Override
    public long getFlag() {
      return flag;
    }

    // optional int32 folderCount = 32;
    public static final int FOLDERCOUNTFIELDNUMBER = 32;
    private int folderCount;
    @Override
    public boolean hasFolderCount() {
      return ((bitField0 & 0x80000000) == 0x80000000);
    }
    @Override
    public int getFolderCount() {
      return folderCount;
    }

    // optional int32 collectionFolderCount = 33;
    public static final int COLLECTIONFOLDERCOUNTFIELDNUMBER = 33;
    private int collectionFolderCount;
    @Override
    public boolean hasCollectionFolderCount() {
      return ((bitField1 & 0x00000001) == 0x00000001);
    }
    @Override
    public int getCollectionFolderCount() {
      return collectionFolderCount;
    }

    // optional int32 collectionReadCount = 34;
    public static final int COLLECTIONREADCOUNTFIELDNUMBER = 34;
    private int collectionReadCount;
    @Override
    public boolean hasCollectionReadCount() {
      return ((bitField1 & 0x00000002) == 0x00000002);
    }
    @Override
    public int getCollectionReadCount() {
      return collectionReadCount;
    }

    // optional int32 status = 35;
    public static final int STATUSFIELDNUMBER = 35;
    private int status;
    @Override
    public boolean hasStatus() {
      return ((bitField1 & 0x00000004) == 0x00000004);
    }
    @Override
    public int getStatus() {
      return status;
    }

    // optional string Uuids = 36;
    public static final int UUIDSFIELDNUMBER = 36;
    private Object uuids;
    @Override
    public boolean hasUuids() {
      return ((bitField1 & 0x00000008) == 0x00000008);
    }
    @Override
    public String getUuids() {
      Object ref = uuids;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuids = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidsBytes() {
      Object ref = uuids;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uuids = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id = 0;
      userId = 0L;
      accountName = "";
      phoneNum = "";
      email = "";
      password = "";
      baseState = 0;
      uuid = 0;
      openId = "";
      type = 0;
      areaIds = "";
      sex = 0;
      birthday = 0L;
      backCover = "";
      announcerType = "";
      likeTags = "";
      likeCount = 0;
      ablumnCount = 0;
      followerCount = 0;
      followCount = 0;
      remark = "";
      shortRemark = "";
      createTime = 0L;
      updateTime = 0L;
      hot = 0;
      nickName = "";
      source = 0;
      state = 0;
      cover = "";
      features = "";
      flag = 0L;
      folderCount = 0;
      collectionFolderCount = 0;
      collectionReadCount = 0;
      status = 0;
      uuids = "";
    }
    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) {
          return isInitialized == 1;
      }

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0 & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id);
      }
      if (((bitField0 & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, userId);
      }
      if (((bitField0 & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAccountNameBytes());
      }
      if (((bitField0 & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPhoneNumBytes());
      }
      if (((bitField0 & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEmailBytes());
      }
      if (((bitField0 & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPasswordBytes());
      }
      if (((bitField0 & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, baseState);
      }
      if (((bitField0 & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, uuid);
      }
      if (((bitField0 & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getOpenIdBytes());
      }
      if (((bitField0 & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, type);
      }
      if (((bitField0 & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getAreaIdsBytes());
      }
      if (((bitField0 & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, sex);
      }
      if (((bitField0 & 0x00001000) == 0x00001000)) {
        output.writeUInt64(13, birthday);
      }
      if (((bitField0 & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getBackCoverBytes());
      }
      if (((bitField0 & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getAnnouncerTypeBytes());
      }
      if (((bitField0 & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getLikeTagsBytes());
      }
      if (((bitField0 & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, likeCount);
      }
      if (((bitField0 & 0x00020000) == 0x00020000)) {
        output.writeInt32(18, ablumnCount);
      }
      if (((bitField0 & 0x00040000) == 0x00040000)) {
        output.writeInt32(19, followerCount);
      }
      if (((bitField0 & 0x00080000) == 0x00080000)) {
        output.writeInt32(20, followCount);
      }
      if (((bitField0 & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, getRemarkBytes());
      }
      if (((bitField0 & 0x00200000) == 0x00200000)) {
        output.writeBytes(22, getShortRemarkBytes());
      }
      if (((bitField0 & 0x00400000) == 0x00400000)) {
        output.writeUInt64(23, createTime);
      }
      if (((bitField0 & 0x00800000) == 0x00800000)) {
        output.writeUInt64(24, updateTime);
      }
      if (((bitField0 & 0x01000000) == 0x01000000)) {
        output.writeInt32(25, hot);
      }
      if (((bitField0 & 0x02000000) == 0x02000000)) {
        output.writeBytes(26, getNickNameBytes());
      }
      if (((bitField0 & 0x04000000) == 0x04000000)) {
        output.writeInt32(27, source);
      }
      if (((bitField0 & 0x08000000) == 0x08000000)) {
        output.writeInt32(28, state);
      }
      if (((bitField0 & 0x10000000) == 0x10000000)) {
        output.writeBytes(29, getCoverBytes());
      }
      if (((bitField0 & 0x20000000) == 0x20000000)) {
        output.writeBytes(30, getFeaturesBytes());
      }
      if (((bitField0 & 0x40000000) == 0x40000000)) {
        output.writeInt64(31, flag);
      }
      if (((bitField0 & 0x80000000) == 0x80000000)) {
        output.writeInt32(32, folderCount);
      }
      if (((bitField1 & 0x00000001) == 0x00000001)) {
        output.writeInt32(33, collectionFolderCount);
      }
      if (((bitField1 & 0x00000002) == 0x00000002)) {
        output.writeInt32(34, collectionReadCount);
      }
      if (((bitField1 & 0x00000004) == 0x00000004)) {
        output.writeInt32(35, status);
      }
      if (((bitField1 & 0x00000008) == 0x00000008)) {
        output.writeBytes(36, getUuidsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) {
          return size;
      }

      size = 0;
      if (((bitField0 & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id);
      }
      if (((bitField0 & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId);
      }
      if (((bitField0 & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAccountNameBytes());
      }
      if (((bitField0 & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPhoneNumBytes());
      }
      if (((bitField0 & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEmailBytes());
      }
      if (((bitField0 & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPasswordBytes());
      }
      if (((bitField0 & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, baseState);
      }
      if (((bitField0 & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, uuid);
      }
      if (((bitField0 & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getOpenIdBytes());
      }
      if (((bitField0 & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, type);
      }
      if (((bitField0 & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getAreaIdsBytes());
      }
      if (((bitField0 & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, sex);
      }
      if (((bitField0 & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(13, birthday);
      }
      if (((bitField0 & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getBackCoverBytes());
      }
      if (((bitField0 & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getAnnouncerTypeBytes());
      }
      if (((bitField0 & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getLikeTagsBytes());
      }
      if (((bitField0 & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, likeCount);
      }
      if (((bitField0 & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, ablumnCount);
      }
      if (((bitField0 & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, followerCount);
      }
      if (((bitField0 & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, followCount);
      }
      if (((bitField0 & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, getRemarkBytes());
      }
      if (((bitField0 & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, getShortRemarkBytes());
      }
      if (((bitField0 & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(23, createTime);
      }
      if (((bitField0 & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(24, updateTime);
      }
      if (((bitField0 & 0x01000000) == 0x01000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(25, hot);
      }
      if (((bitField0 & 0x02000000) == 0x02000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(26, getNickNameBytes());
      }
      if (((bitField0 & 0x04000000) == 0x04000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(27, source);
      }
      if (((bitField0 & 0x08000000) == 0x08000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(28, state);
      }
      if (((bitField0 & 0x10000000) == 0x10000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(29, getCoverBytes());
      }
      if (((bitField0 & 0x20000000) == 0x20000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(30, getFeaturesBytes());
      }
      if (((bitField0 & 0x40000000) == 0x40000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(31, flag);
      }
      if (((bitField0 & 0x80000000) == 0x80000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(32, folderCount);
      }
      if (((bitField1 & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(33, collectionFolderCount);
      }
      if (((bitField1 & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(34, collectionReadCount);
      }
      if (((bitField1 & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(35, status);
      }
      if (((bitField1 & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(36, getUuidsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UserBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UserBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UserBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static UserBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static UserBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UserBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static UserBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UserBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static UserBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static UserBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UserBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements UserBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserProtos.internalstatictutorialUserBeandescriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserProtos.internalstatictutorialUserBeanfieldAccessorTable;
      }

      // Construct using com.lazyaudio.yyting.cache.protobuf.autogenerate.UserProtos.UserBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
      public Builder clear() {
        super.clear();
        id = 0;
        bitField0 = (bitField0 & ~0x00000001);
        userId = 0L;
        bitField0 = (bitField0 & ~0x00000002);
        accountName = "";
        bitField0 = (bitField0 & ~0x00000004);
        phoneNum = "";
        bitField0 = (bitField0 & ~0x00000008);
        email = "";
        bitField0 = (bitField0 & ~0x00000010);
        password = "";
        bitField0 = (bitField0 & ~0x00000020);
        baseState = 0;
        bitField0 = (bitField0 & ~0x00000040);
        uuid = 0;
        bitField0 = (bitField0 & ~0x00000080);
        openId = "";
        bitField0 = (bitField0 & ~0x00000100);
        type = 0;
        bitField0 = (bitField0 & ~0x00000200);
        areaIds = "";
        bitField0 = (bitField0 & ~0x00000400);
        sex = 0;
        bitField0 = (bitField0 & ~0x00000800);
        birthday = 0L;
        bitField0 = (bitField0 & ~0x00001000);
        backCover = "";
        bitField0 = (bitField0 & ~0x00002000);
        announcerType = "";
        bitField0 = (bitField0 & ~0x00004000);
        likeTags = "";
        bitField0 = (bitField0 & ~0x00008000);
        likeCount = 0;
        bitField0 = (bitField0 & ~0x00010000);
        ablumnCount = 0;
        bitField0 = (bitField0 & ~0x00020000);
        followerCount = 0;
        bitField0 = (bitField0 & ~0x00040000);
        followCount = 0;
        bitField0 = (bitField0 & ~0x00080000);
        remark = "";
        bitField0 = (bitField0 & ~0x00100000);
        shortRemark = "";
        bitField0 = (bitField0 & ~0x00200000);
        createTime = 0L;
        bitField0 = (bitField0 & ~0x00400000);
        updateTime = 0L;
        bitField0 = (bitField0 & ~0x00800000);
        hot = 0;
        bitField0 = (bitField0 & ~0x01000000);
        nickName = "";
        bitField0 = (bitField0 & ~0x02000000);
        source = 0;
        bitField0 = (bitField0 & ~0x04000000);
        state = 0;
        bitField0 = (bitField0 & ~0x08000000);
        cover = "";
        bitField0 = (bitField0 & ~0x10000000);
        features = "";
        bitField0 = (bitField0 & ~0x20000000);
        flag = 0L;
        bitField0 = (bitField0 & ~0x40000000);
        folderCount = 0;
        bitField0 = (bitField0 & ~0x80000000);
        collectionFolderCount = 0;
        bitField1 = (bitField1 & ~0x00000001);
        collectionReadCount = 0;
        bitField1 = (bitField1 & ~0x00000002);
        status = 0;
        bitField1 = (bitField1 & ~0x00000004);
        uuids = "";
        bitField1 = (bitField1 & ~0x00000008);
        return this;
      }

      @Override
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserBean.getDescriptor();
      }

      @Override
      public UserBean getDefaultInstanceForType() {
        return UserBean.getDefaultInstance();
      }

      @Override
      public UserBean build() {
        UserBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private UserBean buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        UserBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      @Override
      public UserBean buildPartial() {
        UserBean result = new UserBean(this);
        int frombitField0 = bitField0;
        int frombitField1 = bitField1;
        int tobitField0 = 0;
        int tobitField1 = 0;
        if (((frombitField0 & 0x00000001) == 0x00000001)) {
          tobitField0 |= 0x00000001;
        }
        result.id = id;
        if (((frombitField0 & 0x00000002) == 0x00000002)) {
          tobitField0 |= 0x00000002;
        }
        result.userId = userId;
        if (((frombitField0 & 0x00000004) == 0x00000004)) {
          tobitField0 |= 0x00000004;
        }
        result.accountName = accountName;
        if (((frombitField0 & 0x00000008) == 0x00000008)) {
          tobitField0 |= 0x00000008;
        }
        result.phoneNum = phoneNum;
        if (((frombitField0 & 0x00000010) == 0x00000010)) {
          tobitField0 |= 0x00000010;
        }
        result.email = email;
        if (((frombitField0 & 0x00000020) == 0x00000020)) {
          tobitField0 |= 0x00000020;
        }
        result.password = password;
        if (((frombitField0 & 0x00000040) == 0x00000040)) {
          tobitField0 |= 0x00000040;
        }
        result.baseState = baseState;
        if (((frombitField0 & 0x00000080) == 0x00000080)) {
          tobitField0 |= 0x00000080;
        }
        result.uuid = uuid;
        if (((frombitField0 & 0x00000100) == 0x00000100)) {
          tobitField0 |= 0x00000100;
        }
        result.openId = openId;
        if (((frombitField0 & 0x00000200) == 0x00000200)) {
          tobitField0 |= 0x00000200;
        }
        result.type = type;
        if (((frombitField0 & 0x00000400) == 0x00000400)) {
          tobitField0 |= 0x00000400;
        }
        result.areaIds = areaIds;
        if (((frombitField0 & 0x00000800) == 0x00000800)) {
          tobitField0 |= 0x00000800;
        }
        result.sex = sex;
        if (((frombitField0 & 0x00001000) == 0x00001000)) {
          tobitField0 |= 0x00001000;
        }
        result.birthday = birthday;
        if (((frombitField0 & 0x00002000) == 0x00002000)) {
          tobitField0 |= 0x00002000;
        }
        result.backCover = backCover;
        if (((frombitField0 & 0x00004000) == 0x00004000)) {
          tobitField0 |= 0x00004000;
        }
        result.announcerType = announcerType;
        if (((frombitField0 & 0x00008000) == 0x00008000)) {
          tobitField0 |= 0x00008000;
        }
        result.likeTags = likeTags;
        if (((frombitField0 & 0x00010000) == 0x00010000)) {
          tobitField0 |= 0x00010000;
        }
        result.likeCount = likeCount;
        if (((frombitField0 & 0x00020000) == 0x00020000)) {
          tobitField0 |= 0x00020000;
        }
        result.ablumnCount = ablumnCount;
        if (((frombitField0 & 0x00040000) == 0x00040000)) {
          tobitField0 |= 0x00040000;
        }
        result.followerCount = followerCount;
        if (((frombitField0 & 0x00080000) == 0x00080000)) {
          tobitField0 |= 0x00080000;
        }
        result.followCount = followCount;
        if (((frombitField0 & 0x00100000) == 0x00100000)) {
          tobitField0 |= 0x00100000;
        }
        result.remark = remark;
        if (((frombitField0 & 0x00200000) == 0x00200000)) {
          tobitField0 |= 0x00200000;
        }
        result.shortRemark = shortRemark;
        if (((frombitField0 & 0x00400000) == 0x00400000)) {
          tobitField0 |= 0x00400000;
        }
        result.createTime = createTime;
        if (((frombitField0 & 0x00800000) == 0x00800000)) {
          tobitField0 |= 0x00800000;
        }
        result.updateTime = updateTime;
        if (((frombitField0 & 0x01000000) == 0x01000000)) {
          tobitField0 |= 0x01000000;
        }
        result.hot = hot;
        if (((frombitField0 & 0x02000000) == 0x02000000)) {
          tobitField0 |= 0x02000000;
        }
        result.nickName = nickName;
        if (((frombitField0 & 0x04000000) == 0x04000000)) {
          tobitField0 |= 0x04000000;
        }
        result.source = source;
        if (((frombitField0 & 0x08000000) == 0x08000000)) {
          tobitField0 |= 0x08000000;
        }
        result.state = state;
        if (((frombitField0 & 0x10000000) == 0x10000000)) {
          tobitField0 |= 0x10000000;
        }
        result.cover = cover;
        if (((frombitField0 & 0x20000000) == 0x20000000)) {
          tobitField0 |= 0x20000000;
        }
        result.features = features;
        if (((frombitField0 & 0x40000000) == 0x40000000)) {
          tobitField0 |= 0x40000000;
        }
        result.flag = flag;
        if (((frombitField0 & 0x80000000) == 0x80000000)) {
          tobitField0 |= 0x80000000;
        }
        result.folderCount = folderCount;
        if (((frombitField1 & 0x00000001) == 0x00000001)) {
          tobitField1 |= 0x00000001;
        }
        result.collectionFolderCount = collectionFolderCount;
        if (((frombitField1 & 0x00000002) == 0x00000002)) {
          tobitField1 |= 0x00000002;
        }
        result.collectionReadCount = collectionReadCount;
        if (((frombitField1 & 0x00000004) == 0x00000004)) {
          tobitField1 |= 0x00000004;
        }
        result.status = status;
        if (((frombitField1 & 0x00000008) == 0x00000008)) {
          tobitField1 |= 0x00000008;
        }
        result.uuids = uuids;
        result.bitField0 = tobitField0;
        result.bitField1 = tobitField1;
        onBuilt();
        return result;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserBean) {
          return mergeFrom((UserBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserBean other) {
        if (other == UserBean.getDefaultInstance()) {
            return this;
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasAccountName()) {
          setAccountName(other.getAccountName());
        }
        if (other.hasPhoneNum()) {
          setPhoneNum(other.getPhoneNum());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasBaseState()) {
          setBaseState(other.getBaseState());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasOpenId()) {
          setOpenId(other.getOpenId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAreaIds()) {
          setAreaIds(other.getAreaIds());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasBirthday()) {
          setBirthday(other.getBirthday());
        }
        if (other.hasBackCover()) {
          setBackCover(other.getBackCover());
        }
        if (other.hasAnnouncerType()) {
          setAnnouncerType(other.getAnnouncerType());
        }
        if (other.hasLikeTags()) {
          setLikeTags(other.getLikeTags());
        }
        if (other.hasLikeCount()) {
          setLikeCount(other.getLikeCount());
        }
        if (other.hasAblumnCount()) {
          setAblumnCount(other.getAblumnCount());
        }
        if (other.hasFollowerCount()) {
          setFollowerCount(other.getFollowerCount());
        }
        if (other.hasFollowCount()) {
          setFollowCount(other.getFollowCount());
        }
        if (other.hasRemark()) {
          setRemark(other.getRemark());
        }
        if (other.hasShortRemark()) {
          setShortRemark(other.getShortRemark());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        if (other.hasHot()) {
          setHot(other.getHot());
        }
        if (other.hasNickName()) {
          setNickName(other.getNickName());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasCover()) {
          setCover(other.getCover());
        }
        if (other.hasFeatures()) {
          setFeatures(other.getFeatures());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasFolderCount()) {
          setFolderCount(other.getFolderCount());
        }
        if (other.hasCollectionFolderCount()) {
          setCollectionFolderCount(other.getCollectionFolderCount());
        }
        if (other.hasCollectionReadCount()) {
          setCollectionReadCount(other.getCollectionReadCount());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasUuids()) {
          setUuids(other.getUuids());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0 |= 0x00000001;
              id = input.readInt32();
              break;
            }
            case 16: {
              bitField0 |= 0x00000002;
              userId = input.readInt64();
              break;
            }
            case 26: {
              bitField0 |= 0x00000004;
              accountName = input.readBytes();
              break;
            }
            case 34: {
              bitField0 |= 0x00000008;
              phoneNum = input.readBytes();
              break;
            }
            case 42: {
              bitField0 |= 0x00000010;
              email = input.readBytes();
              break;
            }
            case 50: {
              bitField0 |= 0x00000020;
              password = input.readBytes();
              break;
            }
            case 56: {
              bitField0 |= 0x00000040;
              baseState = input.readInt32();
              break;
            }
            case 64: {
              bitField0 |= 0x00000080;
              uuid = input.readInt32();
              break;
            }
            case 74: {
              bitField0 |= 0x00000100;
              openId = input.readBytes();
              break;
            }
            case 80: {
              bitField0 |= 0x00000200;
              type = input.readInt32();
              break;
            }
            case 90: {
              bitField0 |= 0x00000400;
              areaIds = input.readBytes();
              break;
            }
            case 96: {
              bitField0 |= 0x00000800;
              sex = input.readInt32();
              break;
            }
            case 104: {
              bitField0 |= 0x00001000;
              birthday = input.readUInt64();
              break;
            }
            case 114: {
              bitField0 |= 0x00002000;
              backCover = input.readBytes();
              break;
            }
            case 122: {
              bitField0 |= 0x00004000;
              announcerType = input.readBytes();
              break;
            }
            case 130: {
              bitField0 |= 0x00008000;
              likeTags = input.readBytes();
              break;
            }
            case 136: {
              bitField0 |= 0x00010000;
              likeCount = input.readInt32();
              break;
            }
            case 144: {
              bitField0 |= 0x00020000;
              ablumnCount = input.readInt32();
              break;
            }
            case 152: {
              bitField0 |= 0x00040000;
              followerCount = input.readInt32();
              break;
            }
            case 160: {
              bitField0 |= 0x00080000;
              followCount = input.readInt32();
              break;
            }
            case 170: {
              bitField0 |= 0x00100000;
              remark = input.readBytes();
              break;
            }
            case 178: {
              bitField0 |= 0x00200000;
              shortRemark = input.readBytes();
              break;
            }
            case 184: {
              bitField0 |= 0x00400000;
              createTime = input.readUInt64();
              break;
            }
            case 192: {
              bitField0 |= 0x00800000;
              updateTime = input.readUInt64();
              break;
            }
            case 200: {
              bitField0 |= 0x01000000;
              hot = input.readInt32();
              break;
            }
            case 210: {
              bitField0 |= 0x02000000;
              nickName = input.readBytes();
              break;
            }
            case 216: {
              bitField0 |= 0x04000000;
              source = input.readInt32();
              break;
            }
            case 224: {
              bitField0 |= 0x08000000;
              state = input.readInt32();
              break;
            }
            case 234: {
              bitField0 |= 0x10000000;
              cover = input.readBytes();
              break;
            }
            case 242: {
              bitField0 |= 0x20000000;
              features = input.readBytes();
              break;
            }
            case 248: {
              bitField0 |= 0x40000000;
              flag = input.readInt64();
              break;
            }
            case 256: {
              bitField0 |= 0x80000000;
              folderCount = input.readInt32();
              break;
            }
            case 264: {
              bitField1 |= 0x00000001;
              collectionFolderCount = input.readInt32();
              break;
            }
            case 272: {
              bitField1 |= 0x00000002;
              collectionReadCount = input.readInt32();
              break;
            }
            case 280: {
              bitField1 |= 0x00000004;
              status = input.readInt32();
              break;
            }
            case 290: {
              bitField1 |= 0x00000008;
              uuids = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0;
      private int bitField1;

      // required int32 Id = 1;
      private int id ;
      @Override
      public boolean hasId() {
        return ((bitField0 & 0x00000001) == 0x00000001);
      }
      @Override
      public int getId() {
        return id;
      }
      public Builder setId(int value) {
        bitField0 |= 0x00000001;
        id = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0 = (bitField0 & ~0x00000001);
        id = 0;
        onChanged();
        return this;
      }

      // optional int64 UserId = 2;
      private long userId ;
      @Override
      public boolean hasUserId() {
        return ((bitField0 & 0x00000002) == 0x00000002);
      }
      @Override
      public long getUserId() {
        return userId;
      }
      public Builder setUserId(long value) {
        bitField0 |= 0x00000002;
        userId = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0 = (bitField0 & ~0x00000002);
        userId = 0L;
        onChanged();
        return this;
      }

      // optional string AccountName = 3;
      private Object accountName = "";
      @Override
      public boolean hasAccountName() {
        return ((bitField0 & 0x00000004) == 0x00000004);
      }
      @Override
      public String getAccountName() {
        Object ref = accountName;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountName = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000004;
        accountName = value;
        onChanged();
        return this;
      }
      public Builder clearAccountName() {
        bitField0 = (bitField0 & ~0x00000004);
        accountName = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      void setAccountName(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000004;
        accountName = value;
        onChanged();
      }

      // optional string PhoneNum = 4;
      private Object phoneNum = "";
      @Override
      public boolean hasPhoneNum() {
        return ((bitField0 & 0x00000008) == 0x00000008);
      }
      @Override
      public String getPhoneNum() {
        Object ref = phoneNum;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phoneNum = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhoneNum(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000008;
        phoneNum = value;
        onChanged();
        return this;
      }
      public Builder clearPhoneNum() {
        bitField0 = (bitField0 & ~0x00000008);
        phoneNum = getDefaultInstance().getPhoneNum();
        onChanged();
        return this;
      }
      void setPhoneNum(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000008;
        phoneNum = value;
        onChanged();
      }

      // optional string Email = 5;
      private Object email = "";
      @Override
      public boolean hasEmail() {
        return ((bitField0 & 0x00000010) == 0x00000010);
      }
      @Override
      public String getEmail() {
        Object ref = email;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000010;
        email = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0 = (bitField0 & ~0x00000010);
        email = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000010;
        email = value;
        onChanged();
      }

      // optional string Password = 6;
      private Object password = "";
      @Override
      public boolean hasPassword() {
        return ((bitField0 & 0x00000020) == 0x00000020);
      }
      @Override
      public String getPassword() {
        Object ref = password;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000020;
        password = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0 = (bitField0 & ~0x00000020);
        password = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000020;
        password = value;
        onChanged();
      }

      // optional int32 BaseState = 7;
      private int baseState ;
      @Override
      public boolean hasBaseState() {
        return ((bitField0 & 0x00000040) == 0x00000040);
      }
      @Override
      public int getBaseState() {
        return baseState;
      }
      public Builder setBaseState(int value) {
        bitField0 |= 0x00000040;
        baseState = value;
        onChanged();
        return this;
      }
      public Builder clearBaseState() {
        bitField0 = (bitField0 & ~0x00000040);
        baseState = 0;
        onChanged();
        return this;
      }

      // optional int32 Uuid = 8;
      private int uuid ;
      @Override
      public boolean hasUuid() {
        return ((bitField0 & 0x00000080) == 0x00000080);
      }
      @Override
      public int getUuid() {
        return uuid;
      }
      public Builder setUuid(int value) {
        bitField0 |= 0x00000080;
        uuid = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0 = (bitField0 & ~0x00000080);
        uuid = 0;
        onChanged();
        return this;
      }

      // optional string OpenId = 9;
      private Object openId = "";
      @Override
      public boolean hasOpenId() {
        return ((bitField0 & 0x00000100) == 0x00000100);
      }
      @Override
      public String getOpenId() {
        Object ref = openId;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          openId = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOpenId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000100;
        openId = value;
        onChanged();
        return this;
      }
      public Builder clearOpenId() {
        bitField0 = (bitField0 & ~0x00000100);
        openId = getDefaultInstance().getOpenId();
        onChanged();
        return this;
      }
      void setOpenId(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000100;
        openId = value;
        onChanged();
      }

      // optional int32 Type = 10;
      private int type ;
      @Override
      public boolean hasType() {
        return ((bitField0 & 0x00000200) == 0x00000200);
      }
      @Override
      public int getType() {
        return type;
      }
      public Builder setType(int value) {
        bitField0 |= 0x00000200;
        type = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0 = (bitField0 & ~0x00000200);
        type = 0;
        onChanged();
        return this;
      }

      // optional string AreaIds = 11;
      private Object areaIds = "";
      @Override
      public boolean hasAreaIds() {
        return ((bitField0 & 0x00000400) == 0x00000400);
      }
      @Override
      public String getAreaIds() {
        Object ref = areaIds;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          areaIds = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAreaIds(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00000400;
        areaIds = value;
        onChanged();
        return this;
      }
      public Builder clearAreaIds() {
        bitField0 = (bitField0 & ~0x00000400);
        areaIds = getDefaultInstance().getAreaIds();
        onChanged();
        return this;
      }
      void setAreaIds(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00000400;
        areaIds = value;
        onChanged();
      }

      // optional int32 Sex = 12;
      private int sex ;
      @Override
      public boolean hasSex() {
        return ((bitField0 & 0x00000800) == 0x00000800);
      }
      @Override
      public int getSex() {
        return sex;
      }
      public Builder setSex(int value) {
        bitField0 |= 0x00000800;
        sex = value;
        onChanged();
        return this;
      }
      public Builder clearSex() {
        bitField0 = (bitField0 & ~0x00000800);
        sex = 0;
        onChanged();
        return this;
      }

      // optional uint64 Birthday = 13;
      private long birthday ;
      @Override
      public boolean hasBirthday() {
        return ((bitField0 & 0x00001000) == 0x00001000);
      }
      @Override
      public long getBirthday() {
        return birthday;
      }
      public Builder setBirthday(long value) {
        bitField0 |= 0x00001000;
        birthday = value;
        onChanged();
        return this;
      }
      public Builder clearBirthday() {
        bitField0 = (bitField0 & ~0x00001000);
        birthday = 0L;
        onChanged();
        return this;
      }

      // optional string BackCover = 14;
      private Object backCover = "";
      @Override
      public boolean hasBackCover() {
        return ((bitField0 & 0x00002000) == 0x00002000);
      }
      @Override
      public String getBackCover() {
        Object ref = backCover;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          backCover = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBackCover(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00002000;
        backCover = value;
        onChanged();
        return this;
      }
      public Builder clearBackCover() {
        bitField0 = (bitField0 & ~0x00002000);
        backCover = getDefaultInstance().getBackCover();
        onChanged();
        return this;
      }
      void setBackCover(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00002000;
        backCover = value;
        onChanged();
      }

      // optional string AnnouncerType = 15;
      private Object announcerType = "";
      @Override
      public boolean hasAnnouncerType() {
        return ((bitField0 & 0x00004000) == 0x00004000);
      }
      @Override
      public String getAnnouncerType() {
        Object ref = announcerType;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          announcerType = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAnnouncerType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00004000;
        announcerType = value;
        onChanged();
        return this;
      }
      public Builder clearAnnouncerType() {
        bitField0 = (bitField0 & ~0x00004000);
        announcerType = getDefaultInstance().getAnnouncerType();
        onChanged();
        return this;
      }
      void setAnnouncerType(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00004000;
        announcerType = value;
        onChanged();
      }

      // optional string LikeTags = 16;
      private Object likeTags = "";
      @Override
      public boolean hasLikeTags() {
        return ((bitField0 & 0x00008000) == 0x00008000);
      }
      @Override
      public String getLikeTags() {
        Object ref = likeTags;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          likeTags = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLikeTags(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00008000;
        likeTags = value;
        onChanged();
        return this;
      }
      public Builder clearLikeTags() {
        bitField0 = (bitField0 & ~0x00008000);
        likeTags = getDefaultInstance().getLikeTags();
        onChanged();
        return this;
      }
      void setLikeTags(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00008000;
        likeTags = value;
        onChanged();
      }

      // optional int32 LikeCount = 17;
      private int likeCount ;
      @Override
      public boolean hasLikeCount() {
        return ((bitField0 & 0x00010000) == 0x00010000);
      }
      @Override
      public int getLikeCount() {
        return likeCount;
      }
      public Builder setLikeCount(int value) {
        bitField0 |= 0x00010000;
        likeCount = value;
        onChanged();
        return this;
      }
      public Builder clearLikeCount() {
        bitField0 = (bitField0 & ~0x00010000);
        likeCount = 0;
        onChanged();
        return this;
      }

      // optional int32 AblumnCount = 18;
      private int ablumnCount ;
      @Override
      public boolean hasAblumnCount() {
        return ((bitField0 & 0x00020000) == 0x00020000);
      }
      @Override
      public int getAblumnCount() {
        return ablumnCount;
      }
      public Builder setAblumnCount(int value) {
        bitField0 |= 0x00020000;
        ablumnCount = value;
        onChanged();
        return this;
      }
      public Builder clearAblumnCount() {
        bitField0 = (bitField0 & ~0x00020000);
        ablumnCount = 0;
        onChanged();
        return this;
      }

      // optional int32 FollowerCount = 19;
      private int followerCount ;
      @Override
      public boolean hasFollowerCount() {
        return ((bitField0 & 0x00040000) == 0x00040000);
      }
      @Override
      public int getFollowerCount() {
        return followerCount;
      }
      public Builder setFollowerCount(int value) {
        bitField0 |= 0x00040000;
        followerCount = value;
        onChanged();
        return this;
      }
      public Builder clearFollowerCount() {
        bitField0 = (bitField0 & ~0x00040000);
        followerCount = 0;
        onChanged();
        return this;
      }

      // optional int32 FollowCount = 20;
      private int followCount ;
      @Override
      public boolean hasFollowCount() {
        return ((bitField0 & 0x00080000) == 0x00080000);
      }
      @Override
      public int getFollowCount() {
        return followCount;
      }
      public Builder setFollowCount(int value) {
        bitField0 |= 0x00080000;
        followCount = value;
        onChanged();
        return this;
      }
      public Builder clearFollowCount() {
        bitField0 = (bitField0 & ~0x00080000);
        followCount = 0;
        onChanged();
        return this;
      }

      // optional string Remark = 21;
      private Object remark = "";
      @Override
      public boolean hasRemark() {
        return ((bitField0 & 0x00100000) == 0x00100000);
      }
      @Override
      public String getRemark() {
        Object ref = remark;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          remark = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRemark(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00100000;
        remark = value;
        onChanged();
        return this;
      }
      public Builder clearRemark() {
        bitField0 = (bitField0 & ~0x00100000);
        remark = getDefaultInstance().getRemark();
        onChanged();
        return this;
      }
      void setRemark(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00100000;
        remark = value;
        onChanged();
      }

      // optional string ShortRemark = 22;
      private Object shortRemark = "";
      @Override
      public boolean hasShortRemark() {
        return ((bitField0 & 0x00200000) == 0x00200000);
      }
      @Override
      public String getShortRemark() {
        Object ref = shortRemark;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          shortRemark = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setShortRemark(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x00200000;
        shortRemark = value;
        onChanged();
        return this;
      }
      public Builder clearShortRemark() {
        bitField0 = (bitField0 & ~0x00200000);
        shortRemark = getDefaultInstance().getShortRemark();
        onChanged();
        return this;
      }
      void setShortRemark(com.google.protobuf.ByteString value) {
        bitField0 |= 0x00200000;
        shortRemark = value;
        onChanged();
      }

      // optional uint64 CreateTime = 23;
      private long createTime ;
      @Override
      public boolean hasCreateTime() {
        return ((bitField0 & 0x00400000) == 0x00400000);
      }
      @Override
      public long getCreateTime() {
        return createTime;
      }
      public Builder setCreateTime(long value) {
        bitField0 |= 0x00400000;
        createTime = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0 = (bitField0 & ~0x00400000);
        createTime = 0L;
        onChanged();
        return this;
      }

      // optional uint64 UpdateTime = 24;
      private long updateTime ;
      @Override
      public boolean hasUpdateTime() {
        return ((bitField0 & 0x00800000) == 0x00800000);
      }
      @Override
      public long getUpdateTime() {
        return updateTime;
      }
      public Builder setUpdateTime(long value) {
        bitField0 |= 0x00800000;
        updateTime = value;
        onChanged();
        return this;
      }
      public Builder clearUpdateTime() {
        bitField0 = (bitField0 & ~0x00800000);
        updateTime = 0L;
        onChanged();
        return this;
      }

      // optional int32 Hot = 25;
      private int hot ;
      @Override
      public boolean hasHot() {
        return ((bitField0 & 0x01000000) == 0x01000000);
      }
      @Override
      public int getHot() {
        return hot;
      }
      public Builder setHot(int value) {
        bitField0 |= 0x01000000;
        hot = value;
        onChanged();
        return this;
      }
      public Builder clearHot() {
        bitField0 = (bitField0 & ~0x01000000);
        hot = 0;
        onChanged();
        return this;
      }

      // optional string NickName = 26;
      private Object nickName = "";
      @Override
      public boolean hasNickName() {
        return ((bitField0 & 0x02000000) == 0x02000000);
      }
      @Override
      public String getNickName() {
        Object ref = nickName;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickName = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x02000000;
        nickName = value;
        onChanged();
        return this;
      }
      public Builder clearNickName() {
        bitField0 = (bitField0 & ~0x02000000);
        nickName = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      void setNickName(com.google.protobuf.ByteString value) {
        bitField0 |= 0x02000000;
        nickName = value;
        onChanged();
      }

      // optional int32 Source = 27;
      private int source ;
      @Override
      public boolean hasSource() {
        return ((bitField0 & 0x04000000) == 0x04000000);
      }
      @Override
      public int getSource() {
        return source;
      }
      public Builder setSource(int value) {
        bitField0 |= 0x04000000;
        source = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0 = (bitField0 & ~0x04000000);
        source = 0;
        onChanged();
        return this;
      }

      // optional int32 State = 28;
      private int state ;
      @Override
      public boolean hasState() {
        return ((bitField0 & 0x08000000) == 0x08000000);
      }
      @Override
      public int getState() {
        return state;
      }
      public Builder setState(int value) {
        bitField0 |= 0x08000000;
        state = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0 = (bitField0 & ~0x08000000);
        state = 0;
        onChanged();
        return this;
      }

      // optional string Cover = 29;
      private Object cover = "";
      @Override
      public boolean hasCover() {
        return ((bitField0 & 0x10000000) == 0x10000000);
      }
      @Override
      public String getCover() {
        Object ref = cover;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cover = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCover(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x10000000;
        cover = value;
        onChanged();
        return this;
      }
      public Builder clearCover() {
        bitField0 = (bitField0 & ~0x10000000);
        cover = getDefaultInstance().getCover();
        onChanged();
        return this;
      }
      void setCover(com.google.protobuf.ByteString value) {
        bitField0 |= 0x10000000;
        cover = value;
        onChanged();
      }

      // optional string Features = 30;
      private Object features = "";
      @Override
      public boolean hasFeatures() {
        return ((bitField0 & 0x20000000) == 0x20000000);
      }
      @Override
      public String getFeatures() {
        Object ref = features;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          features = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFeatures(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0 |= 0x20000000;
        features = value;
        onChanged();
        return this;
      }
      public Builder clearFeatures() {
        bitField0 = (bitField0 & ~0x20000000);
        features = getDefaultInstance().getFeatures();
        onChanged();
        return this;
      }
      void setFeatures(com.google.protobuf.ByteString value) {
        bitField0 |= 0x20000000;
        features = value;
        onChanged();
      }

      // optional int64 Flag = 31;
      private long flag ;
      @Override
      public boolean hasFlag() {
        return ((bitField0 & 0x40000000) == 0x40000000);
      }
      @Override
      public long getFlag() {
        return flag;
      }
      public Builder setFlag(long value) {
        bitField0 |= 0x40000000;
        flag = value;
        onChanged();
        return this;
      }
      public Builder clearFlag() {
        bitField0 = (bitField0 & ~0x40000000);
        flag = 0L;
        onChanged();
        return this;
      }

      // optional int32 folderCount = 32;
      private int folderCount ;
      @Override
      public boolean hasFolderCount() {
        return ((bitField0 & 0x80000000) == 0x80000000);
      }
      @Override
      public int getFolderCount() {
        return folderCount;
      }
      public Builder setFolderCount(int value) {
        bitField0 |= 0x80000000;
        folderCount = value;
        onChanged();
        return this;
      }
      public Builder clearFolderCount() {
        bitField0 = (bitField0 & ~0x80000000);
        folderCount = 0;
        onChanged();
        return this;
      }

      // optional int32 collectionFolderCount = 33;
      private int collectionFolderCount ;
      @Override
      public boolean hasCollectionFolderCount() {
        return ((bitField1 & 0x00000001) == 0x00000001);
      }
      @Override
      public int getCollectionFolderCount() {
        return collectionFolderCount;
      }
      public Builder setCollectionFolderCount(int value) {
        bitField1 |= 0x00000001;
        collectionFolderCount = value;
        onChanged();
        return this;
      }
      public Builder clearCollectionFolderCount() {
        bitField1 = (bitField1 & ~0x00000001);
        collectionFolderCount = 0;
        onChanged();
        return this;
      }

      // optional int32 collectionReadCount = 34;
      private int collectionReadCount ;
      @Override
      public boolean hasCollectionReadCount() {
        return ((bitField1 & 0x00000002) == 0x00000002);
      }
      @Override
      public int getCollectionReadCount() {
        return collectionReadCount;
      }
      public Builder setCollectionReadCount(int value) {
        bitField1 |= 0x00000002;
        collectionReadCount = value;
        onChanged();
        return this;
      }
      public Builder clearCollectionReadCount() {
        bitField1 = (bitField1 & ~0x00000002);
        collectionReadCount = 0;
        onChanged();
        return this;
      }

      // optional int32 status = 35;
      private int status ;
      @Override
      public boolean hasStatus() {
        return ((bitField1 & 0x00000004) == 0x00000004);
      }
      @Override
      public int getStatus() {
        return status;
      }
      public Builder setStatus(int value) {
        bitField1 |= 0x00000004;
        status = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField1 = (bitField1 & ~0x00000004);
        status = 0;
        onChanged();
        return this;
      }

      // optional string Uuids = 36;
      private Object uuids = "";
      @Override
      public boolean hasUuids() {
        return ((bitField1 & 0x00000008) == 0x00000008);
      }
      @Override
      public String getUuids() {
        Object ref = uuids;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uuids = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuids(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField1 |= 0x00000008;
        uuids = value;
        onChanged();
        return this;
      }
      public Builder clearUuids() {
        bitField1 = (bitField1 & ~0x00000008);
        uuids = getDefaultInstance().getUuids();
        onChanged();
        return this;
      }
      void setUuids(com.google.protobuf.ByteString value) {
        bitField1 |= 0x00000008;
        uuids = value;
        onChanged();
      }

      // @@protocinsertionpoint(builderscope:tutorial.UserBean)
    }

    static {
      DEFAULTINSTANCE = new UserBean(true);
      DEFAULTINSTANCE.initFields();
    }

    // @@protocinsertionpoint(classscope:tutorial.UserBean)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internalstatictutorialUserBeandescriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalstatictutorialUserBeanfieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nuser.proto\022\010tutorial\"\227\005\n\010UserBean\022\n\n\002I" +
      "d\030\001 \002(\005\022\016\n\006UserId\030\002 \001(\003\022\023\n\013AccountName\030\003" +
      " \001(\t\022\020\n\010PhoneNum\030\004 \001(\t\022\r\n\005Email\030\005 \001(\t\022\020\n" +
      "\010Password\030\006 \001(\t\022\021\n\tBaseState\030\007 \001(\005\022\014\n\004Uu" +
      "id\030\010 \001(\005\022\016\n\006OpenId\030\t \001(\t\022\014\n\004Type\030\n \001(\005\022\017" +
      "\n\007AreaIds\030\013 \001(\t\022\013\n\003Sex\030\014 \001(\005\022\020\n\010Birthday" +
      "\030\r \001(\004\022\021\n\tBackCover\030\016 \001(\t\022\025\n\rAnnouncerTy" +
      "pe\030\017 \001(\t\022\020\n\010LikeTags\030\020 \001(\t\022\021\n\tLikeCount\030" +
      "\021 \001(\005\022\023\n\013AblumnCount\030\022 \001(\005\022\025\n\rFollowerCo" +
      "unt\030\023 \001(\005\022\023\n\013FollowCount\030\024 \001(\005\022\016\n\006Remark",
      "\030\025 \001(\t\022\023\n\013ShortRemark\030\026 \001(\t\022\022\n\nCreateTim" +
      "e\030\027 \001(\004\022\022\n\nUpdateTime\030\030 \001(\004\022\013\n\003Hot\030\031 \001(\005" +
      "\022\020\n\010NickName\030\032 \001(\t\022\016\n\006Source\030\033 \001(\005\022\r\n\005St" +
      "ate\030\034 \001(\005\022\r\n\005Cover\030\035 \001(\t\022\020\n\010Features\030\036 \001" +
      "(\t\022\014\n\004Flag\030\037 \001(\003\022\023\n\013folderCount\030  \001(\005\022\035\n" +
      "\025collectionFolderCount\030! \001(\005\022\033\n\023collecti" +
      "onReadCount\030\" \001(\005\022\016\n\006status\030# \001(\005\022\r\n\005Uui" +
      "ds\030$ \001(\tB>\n0com.lazyaudio.yyting.cache.p" +
      "rotobuf.autogenerateB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internalstatictutorialUserBeandescriptor =
            getDescriptor().getMessageTypes().get(0);
          internalstatictutorialUserBeanfieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internalstatictutorialUserBeandescriptor,
              new String[] { "Id", "UserId", "AccountName", "PhoneNum", "Email", "Password", "BaseState", "Uuid", "OpenId", "Type", "AreaIds", "Sex", "Birthday", "BackCover", "AnnouncerType", "LikeTags", "LikeCount", "AblumnCount", "FollowerCount", "FollowCount", "Remark", "ShortRemark", "CreateTime", "UpdateTime", "Hot", "NickName", "Source", "State", "Cover", "Features", "Flag", "FolderCount", "CollectionFolderCount", "CollectionReadCount", "Status", "Uuids", },
              UserBean.class,
             UserBean.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protocinsertionpoint(outerclassscope)
}